#include<stdio.h>
int i=0;
void hailstones(int n)
{
 while(n!=1)
 {

     if(i%3==0)
 printf("\n");
 printf("%d\t",n);
 if(n%2==0)
 n=n/2;
 else
 n=3*n+1;
 i=i+1;

 
 }
 printf("\n");
 if(n==1)
 {
            printf("THE SEQUENCE TERMINATEDAT THE TERM INDEXED:%d",i);
}
}
int main()
{
 int num;
 printf("EnterAn integer: ");
 scanf("%d",&num);
 printf("\nHailstones generated by %d: ",num);
 printf("\n");
 hailstones(num);
 printf("\n\nNumber of hailstones generated: %d",i);
 return 0;
}
